### ISSUE TITLE
Updater is picking the wrong binary

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/azul-zulu#322]
## Expected Behavior

We ship a standard Azul JDK.

## Current Behavior

The updater is picking Azul's JDK with crac in it for Java 17.

See this PR: https://github.com/paketo-buildpacks/azul-zulu/pull/321/files#diff-5f54cb49d0e28117084fad482c0daf89502d4ecb329230071fcf78e56dc939b3R204

## Possible Solution

Fix the updater action so it picks the right version: https://github.com/paketo-buildpacks/pipeline-builder/blob/main/actions/azul-zulu-dependency/main.go

**Comment by anthonydahanne** [comment]
yes, I confirm, 
https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?arch=x86&ext=tar.gz&hw_bitness=64&os=linux&javafx=false&features=jdk&jdk_version=17
returns a crac version


But I think the focus of this issue should rather be on adopting Azul Zulu new `metadata` API, as documented here: https://docs.azul.com/core/metadata-api-migration.html that replaces the former `download` API.

In that case, that's the URL that should be sent by our updater: 
https://api.azul.com/metadata/v1/zulu/packages/?java_version=17&os=linux-glibc&arch=amd64&java_package_type=jdk&javafx_bundled=false&release_status=ga&availability_types=CA&certifications=tck&page=1&crac_supported=false&archive_type=tar.gz&latest=true
